inherit_from:
  - .rubocop_airbnb.yml
  - .rubocop_todo.yml

Rails:
  Enabled: true

AllCops:
  Exclude:      
    - config/spring.rb
    - db/migrate/20180921154144_transform_tax_rate_category_relation.spree.rb
    - db/migrate/20210516054806_create_active_storage_variant_records.active_storage.rb
    - db/samples/assets.rb
    - vendor/**/*
  NewCops: enable

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: no_comma

