inherit_from:
  - .rubocop_airbnb.yml
  - .rubocop_todo.yml

Rails:
  Enabled: true

AllCops:
  Exclude:      
    - config/spring.rb
    - db/migrate/20180921154144_transform_tax_rate_category_relation.spree.rb
    - db/migrate/20210516054806_create_active_storage_variant_records.active_storage.rb
    - db/samples/assets.rb
    - vendor/**/*
  NewCops: enable

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: no_comma

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

Style/PercentLiteralDelimiters:
  Exclude:
    - 'db/migrate/20190912232417_remove_code_from_spree_promotions.spree.rb'
    - 'db/samples/product_properties.rb'

Style/RedundantBegin:
  Exclude:
    - 'bin/yarn'

Style/StderrPuts:
  Exclude:
    - 'bin/yarn'

Layout/LineLength:
  Max: 307

Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - 'db/migrate/20180922105239_create_active_storage_tables.active_storage.rb'
    - 'db/migrate/20210514082210_create_action_mailbox_tables.action_mailbox.rb'
    - 'db/migrate/20210514082211_create_action_text_tables.action_text.rb'

Layout/EmptyLineAfterMagicComment:
  Exclude:
    - 'db/migrate/20190912232419_add_reset_password_token_index_to_spree_users.solidus_auth.rb'

Lint/AssignmentInCondition:
  Exclude:
    - 'db/migrate/20210516054805_add_service_name_to_active_storage_blobs.active_storage.rb'

